[project]
name = "neu-nlp-accelerateviamoe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "torch==1.13.1",
    "torchaudio",
    "torchvision",
    "torch_geometric==2.4.0",
    "transformers==4.31.0",
    "accelerate==0.20.3",
    "tokenizers==0.13.3",
    "safetensors==0.3.1",
    "thop",
    "opencv-python",
    "albumentations==1.3.0",
    "Pillow==10.2.0",
    "imageio==2.22.4",
    "tifffile==2022.10.10",
    "nltk==3.8.1",
    "sacrebleu==2.4.0",
    "numpy==1.23.5",
    "pandas==1.5.1",
    "scikit-learn==1.1.3",
    "imbalanced-learn==0.10.0",
    "matplotlib==3.6.2",
    "jupyter",
    "ipykernel",
    "tqdm",
    "regex",
    "requests",
    "certifi==2022.9.24",
    "click==8.1.3",
    "omegaconf==2.0.6",
    "hydra-core==1.0.7",
    "filelock==3.12.1",
    "wandb==0.15.4 ",
    "termcolor==2.3.0",
    "PyYAML>=6.0.1",
    "typing_extensions==4.4.0",
    "python-dateutil==2.8.2",
    "pkgutil_resolve_name==1.3.10",
    "six==1.16.0",
    "cython==3.0.7",
    "protobuf==4.23.2",
    "python-dotenv>=1.0.1",
    "pyqt6>=6.7.1",
]
